# Generated by Django 4.2.6 on 2023-11-10 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0002_rename_category_books_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='in_stock',
            field=models.BooleanField(default=False),
        ),
    ]
