# Generated by Django 4.2.7 on 2023-11-23 00:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('biblioteca', '0004_books_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='user',
        ),
        migrations.CreateModel(
            name='BooksLoaned',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('returned', models.BooleanField(default=False)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.books')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BookLoaned',
                'verbose_name_plural': 'BooksLoaned',
            },
        ),
    ]
