# Generated by Django 4.2.7 on 2023-11-30 16:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0006_booksloaned_date_loan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booksloaned',
            name='date_loan',
            field=models.DateField(default=datetime.datetime(2023, 11, 30, 13, 1, 26, 820913)),
        ),
    ]
